CREATE PROCEDURE SP_INCLUIR_EVENTO
    @_NOME      NVARCHAR(100),
    @_DECRICAO  NVARCHAR(300),
    @_LOCAL     NVARCHAR(300),
    @_PARTICIPANTES NVARCHAR(150),
    @_DATA          DATE,
    @_TIPO          INT,
    @_HORA          TIME

    AS
    BEGIN
        BEGIN TRANSACTION 

        INSERT INTO TBL_EVENTOS
        (IDEVENTO, NOME, DESCRICAO, LOCAL, PARTICIPANTES, DATA, TIPO, HORA)
        VALUES
        (NEWID(), @_NOME, @_DECRICAO, @_LOCAL, @_PARTICIPANTES, @_DATA, @_TIPO, @_HORA)


        COMMIT

    END